import mongoose from 'mongoose';
import { normalizeToDateOnly } from '../lib/dateUtils.js';

const DriverSchema = new mongoose.Schema({
  id: Number,
  username: { type: String, unique: true, sparse: true },
  mobile: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  status: { type: String, default: 'pending', enum: ['pending', 'active', 'inactive', 'suspended'] },
  kycStatus: { type: String, default: 'pending', enum: ['pending', 'verified', 'rejected', 'incomplete'] },
  signupDate: { type: Date, default: Date.now },
  registrationCompleted: { type: Boolean, default: false }, // Track if registration form was filled
  name: String,
  email: String,
  phone: String,
  dateOfBirth: String,
  address: String,
  city: String,
  state: String,
  pincode: String,
  latitude: String,
  longitude: String,
  emergencyContact: String,
  emergencyContactSecondary: String,
  emergencyRelation: String,
  emergencyRelationSecondary: String,
  emergencyPhone: String,
  emergencyPhoneSecondary: String,
  employeeId: String,
  // External IDs from fleet spreadsheets
  udbId: String,
  driverNo: String,
  alternateNo: String,
  deposit: Number,
  licenseNumber: String,
  licenseExpiryDate: String,
  licenseClass: String,
  aadharNumber: String,
  panNumber: String,
  electricBillNo: String,
  experience: String,
  previousEmployment: String,
  planType: String,
  vehiclePreference: String,
  bankName: String,
  accountNumber: String,
  ifscCode: String,
  accountHolderName: String,
  accountBranchName: String,
  profilePhoto: String,
  signature: String, // URL or base64-encoded signature image
  licenseDocument: String,
  aadharDocument: String,
  aadharDocumentBack: String,
  panDocument: String,
  bankDocument: String,
  electricBillDocument: String,
  joinDate: { type: String, default: () => new Date().toISOString().split('T')[0], set: v => normalizeToDateOnly(v) },
  lastActive: String,
  vehicleAssigned: String,
  totalEarnings: Number,
  rating: Number,
  totalTrips: Number,
  currentPlan: String,
  planAmount: Number,
  documents: Object
}, { timestamps: true, strict: false });

export default mongoose.models.Driver || mongoose.model('Driver', DriverSchema);
